apiVersion: v1
kind: Service
metadata:
  name: gyro
  labels:
    app: gyro
spec:
  ports:
  - port: 8080
    protocol: TCP
  clusterIP: None
  selector:
    app: gyro
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gyro
  labels:
    app: gyro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gyro
  template:
    metadata:
      labels:
        app: gyro
    spec:
      containers:
      - name: gyro
        image: gyro
